# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Song.destroy_all
User.destroy_all


Song.create(title: "Old Town Road (feat. Billy Ray Cyrus)", artist: "Lil Nas X", mood: "Lit", genre: "Country", url: "https://www.youtube.com/embed/UF3Ueqww7M8")
Song.create(title: "Speechless", artist: "Dan + Shay", mood: "Happy", genre: "Country", url: "https://www.youtube.com/embed/7UoP9ABJXGE")
Song.create(title: "Tequila", artist: "Dan + Shay", mood: "Lit", genre: "Country", url: "https://www.youtube.com/embed/c4qgqNS_20s")
Song.create(title: "Crash My Party", artist: "Luke Bryan", mood: "Happy", genre: "Country", url: "https://www.youtube.com/embed/1WEpLzsdEeY")
Song.create(title: "Make It Sweet", artist: "Old Dominion", mood: "Happy", genre: "Country", url: "https://www.youtube.com/embed/CJ9L4PewTuY")
Song.create(title: "Hotel Key", artist: "Old Dominion", mood: "Happy", genre: "Country", url: "https://www.youtube.com/embed/qZIx9CRRSq8")
Song.create(title: "Cruise", artist: "Florida Georgia Line", mood: "Lit", genre: "Country", url: "https://www.youtube.com/embed/8PvebsWcpto")
Song.create(title: "This Is How We Roll ft. Luke Bryan", artist: "Florida Georgia Line", mood: "Lit", genre: "Country", url: "https://www.youtube.com/embed/CbxuXq_981s")
Song.create(title: "Bless the Broken Road", artist: "Rascal Flatts", mood: "Happy", genre: "Country", url: "https://www.youtube.com/embed/Do32g82qilk")
Song.create(title: "Love Wins", artist: "Carrie Underwood", mood: "Lit", genre: "Country", url: "https://www.youtube.com/embed/-Py8OWAMkns")
Song.create(title: "House Party", artist: "Sam Hunt", mood: "Lit", genre: "Country", url: "https://www.youtube.com/embed/1FhRhzAWzLA")
Song.create(title: "Wanted", artist: "Hunter Hayes", mood: "Happy", genre: "Country", url: "https://www.youtube.com/embed/ruyaKdPfTN4")
Song.create(title: "Heaven", artist: "Kane Brown", mood: "Happy", genre: "Country", url: "https://www.youtube.com/embed/dRX0wDNK6S4")
Song.create(title: "Smile", artist: "Uncle Kracker", mood: "Happy", genre: "Country", url: "https://www.youtube.com/embed/ffej15-Dgl0")
Song.create(title: "Drift Away", artist: "Uncle Kracker", mood: "Lit", genre: "Country", url: "https://www.youtube.com/embed/A69BertdSt4")

Song.create(title: "Best Song Ever", artist: "One Direction", mood: "Happy", genre: "Pop", url: "https://www.youtube.com/embed/o_v9MY_FMcw")
Song.create(title: "Beautiful Soul", artist: "Jesse McCartney", mood: "Relaxed", genre: "Pop", url: "https://www.youtube.com/embed/ek2PDE1cAyY")
Song.create(title: "Domino", artist: "Jessie J", mood: "Lit", genre: "Pop", url: "https://www.youtube.com/embed/UJtB55MaoD0")
Song.create(title: "Teenage Dream", artist: "Katy Perry", mood: "Lit", genre: "Pop", url: "https://www.youtube.com/embed/98WtmW-lfeE")
Song.create(title: "Party In The U.S.A.", artist: "Miley Cyrus", mood: "Lit", genre: "Pop", url: "https://www.youtube.com/embed/M11SvDtPBhA")
Song.create(title: "Love Story", artist: "Taylor Swift", mood: "Happy", genre: "Pop", url: "https://www.youtube.com/embed/8xg3vE8Ie_E")
Song.create(title: "Love Yourself", artist: "Justin Bieber", mood: "Relaxed", genre: "Pop", url: "https://www.youtube.com/embed/oyEuk8j8imI")
Song.create(title: "Toxic", artist: "Britney Spears", mood: "Angry", genre: "Pop", url: "https://www.youtube.com/embed/LOZuxwVk7TU")
Song.create(title: "I Want It That Way", artist: "Backstreet Boys", mood: "Sad", genre: "Pop", url: "https://www.youtube.com/embed/4fndeDfaWCg")
Song.create(title: "Tearin' Up My Heart", artist: "*NSYNC", mood: "Sad", genre: "Pop", url: "https://www.youtube.com/embed/_ZcmuKsyvzg")
Song.create(title: "Can't Stop The Feeling", artist: "Justin Timberlake", mood: "Happy", genre: "Pop", url: "https://www.youtube.com/embed/ru0K8uYEZWw")
Song.create(title: "Bad Blood", artist: "Taylor Swift", mood: "Angry", genre: "Pop", url: "https://www.youtube.com/embed/QcIy9NiNbmo")
Song.create(title: "Bad Romance", artist: "Lady Gaga", mood: "Angry", genre: "Pop", url: "https://www.youtube.com/embed/qrO4YZeyl0I")
Song.create(title: "TiK ToK", artist: "Ke$ha", mood: "Lit", genre: "Pop", url: "https://www.youtube.com/embed/iP6XpLQM2Cs")
Song.create(title: "Call Me Maybe", artist: "Carly Rae Jepsen", mood: "Happy", genre: "Pop", url: "https://www.youtube.com/embed/fWNaR-rxAic")
Song.create(title: "Shape Of You", artist: "Ed Sheeran", mood: "Relaxed", genre: "Pop", url: "https://www.youtube.com/embed/JGwWNGJdvx8")
Song.create(title: "Perfect", artist: "Ed Sheeran", mood: "Relaxed", genre: "Pop", url: "https://www.youtube.com/embed/2Vv-BfVoq4g")
Song.create(title: "Hello", artist: "Adele", mood: "Sad", genre: "Pop", url: "https://www.youtube.com/embed/YQHsXMglC9A")
Song.create(title: "Sad Song ft. Elena Coats", artist: "We The Kings", mood: "Sad", genre: "Pop", url: "https://www.youtube.com/embed/BZsXcc_tC-o")
Song.create(title: "See You Again ft. Charlie Puth", artist: "Wiz Khalifa", mood: "Sad", genre: "Pop", url: "https://www.youtube.com/embed/RgKAFK5djSk")
Song.create(title: "Dark Horse", artist: "Katy Perry", mood: "Angry", genre: "Pop", url: "https://www.youtube.com/embed/0KSOMA3QBU0")
Song.create(title: "The Way", artist: "Ariana Grande", mood: "Happy", genre: "Pop", url: "https://www.youtube.com/embed/_sV0S8qWSy0")
Song.create(title: "Cry Me A River", artist: "Justin Timberlake", mood: "Angry", genre: "Pop", url: "https://www.youtube.com/embed/DksSPZTZES0")
Song.create(title: "Bleeding Love", artist: "Leona Lewis", mood: "Sad", genre: "Pop", url: "https://www.youtube.com/embed/7_weSk0BonM")
Song.create(title: "Just A Dream", artist: "Nelly", mood: "Sad", genre: "Pop", url: "https://www.youtube.com/embed/N6O2ncUKvlg")
Song.create(title: "Raise Your Glass", artist: "P!nk", mood: "Lit", genre: "Pop", url: "https://www.youtube.com/embed/XjVNlG5cZyQ")
Song.create(title: "A Thousand Miles", artist: "Vanessa Carlton", mood: "Relaxed", genre: "Pop", url: "https://www.youtube.com/embed/Cwkej79U3ek")
Song.create(title: "Because Of You", artist: "Kelly Clarkson", mood: "Angry", genre: "Pop", url: "https://www.youtube.com/embed/Ra-Om7UMSJc")
Song.create(title: "(You Drive Me) Crazy", artist: "Britney Spears", mood: "Happy", genre: "Pop", url: "https://www.youtube.com/embed/Q4VK9_CfOLQ")
Song.create(title: "Pocketful of Sunshine", artist: "Natasha Bedingfield", mood: "Happy", genre: "Pop", url: "https://www.youtube.com/embed/gte3BoXKwP0")
Song.create(title: "Genie in a Bottle", artist: "Christina Aguilera", mood: "Lit", genre: "Pop", url: "https://www.youtube.com/embed/kIDWgqDBNXA")
Song.create(title: "Wannabe", artist: "Spice Girls", mood: "Lit", genre: "Pop", url: "https://www.youtube.com/embed/gJLIiF15wjQ")
Song.create(title: "Be Alright", artist: "Ariana Grande", mood: "Relaxed", genre: "Pop", url: "https://www.youtube.com/embed/eBAHqRnSgRw")
Song.create(title: "Take A Bow", artist: "Rihanna", mood: "Angry", genre: "Pop", url: "https://www.youtube.com/embed/J3UjJ4wKLkg")
Song.create(title: "What Makes You Beautiful", artist: "One Direction", mood: "Relaxed", genre: "Pop", url: "https://www.youtube.com/embed/QJO3ROT-A4E")


rock 2 lit, 2 happy, 1 angry, 1 relaxed

Song.create(title: "Perfect", artist: "Simple Plan", mood: "Sad", genre: "Rock", url: "https://www.youtube.com/embed/RUi54JTgL5s")
Song.create(title: "Untitled", artist: "Simple Plan", mood: "Sad", genre: "Rock", url: "https://www.youtube.com/embed/ZQ7oqmikZDQ")
Song.create(title: "I'd Do Anything", artist: "Simple Plan", mood: "Lit", genre: "Rock", url: "https://www.youtube.com/embed/H2M7zo8ZziE")
Song.create(title: "Numb", artist: "Linkin Park", mood: "Angry", genre: "Rock", url: "https://www.youtube.com/embed/kXYiU_JCYtU")
Song.create(title: "Crawling", artist: "Linkin Park", mood: "Angry", genre: "Rock", url: "https://www.youtube.com/embed/Gd9OhYroLN0")
Song.create(title: "American Idiot", artist: "Green Day", mood: "Lit", genre: "Rock", url: "https://www.youtube.com/embed/Ee_uujKuJMI")
Song.create(title: "Boulevard Of Broken Dreams", artist: "Green Day", mood: "Sad", genre: "Rock", url: "https://www.youtube.com/embed/Soa3gO7tL-c")
Song.create(title: "I Miss You", artist: "Blink-182", mood: "Sad", genre: "Rock", url: "https://www.youtube.com/embed/s1tAYmMjLdY")
Song.create(title: "All The Small Things", artist: "Blink-182", mood: "Happy", genre: "Rock", url: "https://www.youtube.com/embed/9Ht5RZpzPqw")
Song.create(title: "Always", artist: "Blink-182", mood: "Relaxed", genre: "Rock", url: "https://www.youtube.com/embed/CvtJVku_mJw")
Song.create(title: "All Star", artist: "Smash Mouth", mood: "Relaxed", genre: "Rock", url: "https://www.youtube.com/embed/L_jWHffIx5E")
Song.create(title: "I'm A Believer", artist: "Smash Mouth", mood: "Happy", genre: "Rock", url: "https://www.youtube.com/embed/0mYBSayCsH0")
Song.create(title: "In Too Deep", artist: "Sum 41", mood: "Lit", genre: "Rock", url: "https://www.youtube.com/embed/emGri7i8Y2Y")
Song.create(title: "The Middle", artist: "Jimmy Eat World", mood: "Happy", genre: "Rock", url: "https://www.youtube.com/embed/oKsxPW6i3pM")
Song.create(title: "Stacy's Mom", artist: "Fountains of Wayne", mood: "Lit", genre: "Rock", url: "https://www.youtube.com/embed/dZLfasMPOU4")
Song.create(title: "Ocean Avenue", artist: "Yellowcard", mood: "Relaxed", genre: "Rock", url: "https://www.youtube.com/embed/X9fLbfzCqWw")
Song.create(title: "1985", artist: "Bowling For Soup", mood: "Relaxed", genre: "Rock", url: "https://www.youtube.com/embed/K38xNqZvBJI")
Song.create(title: "Be My Escape", artist: "Relient K", mood: "Sad", genre: "Rock", url: "https://www.youtube.com/embed/lt-FPtnyxvs")
Song.create(title: "Who I Am Hates Who I've Been", artist: "Relient K", mood: "Angry", genre: "Rock", url: "https://www.youtube.com/embed/8HeuMiuj_Sg")
Song.create(title: "Mr. Brightside", artist: "The Killers", mood: "Angry", genre: "Rock", url: "https://www.youtube.com/embed/gGdGFtwCNBE")
Song.create(title: "Let It Be", artist: "The Beatles", mood: "Relaxed", genre: "Rock", url: "https://www.youtube.com/embed/QDYfEBY9NM4")
Song.create(title: "Wonderwall", artist: "Oasis", mood: "Relaxed", genre: "Rock", url: "https://www.youtube.com/embed/bx1Bh8ZvH84")
Song.create(title: "Complicated", artist: "Avril Lavigne", mood: "Angry", genre: "Rock", url: "https://www.youtube.com/embed/5NPBIwQyPWE")
Song.create(title: "Iris", artist: "Goo Goo Dolls", mood: "Sad", genre: "Rock", url: "https://www.youtube.com/embed/NdYWuo9OFAw")
Song.create(title: "How to Save a Life", artist: "The Fray", mood: "Sad", genre: "Rock", url: "https://www.youtube.com/embed/cjVQ36NhbMk")
Song.create(title: "You and Me", artist: "Lifehouse", mood: "Happy", genre: "Rock", url: "https://www.youtube.com/embed/ac3HkriqdGQ")
Song.create(title: "It's My Life", artist: "Bon Jovi", mood: "Lit", genre: "Rock", url: "https://www.youtube.com/embed/vx2u5uUu3DE")
Song.create(title: "Livin' On A Prayer", artist: "Bon Jovi", mood: "Happy", genre: "Rock", url: "https://www.youtube.com/embed/lDK9QqIzhwk")
Song.create(title: "The Pretender", artist: "Foo Fighters", mood: "Angry", genre: "Rock", url: "https://www.youtube.com/embed/SBjQ9tuuTJQ")



