# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Song.destroy_all
User.destroy_all


Song.create(title: "Old Town Road (feat. Billy Ray Cyrus)", artist: "Lil Nas X", mood: "Lit", genre: "Country", url: "https://www.youtube.com/embed/UF3Ueqww7M8")
Song.create(title: "Speechless", artist: "Dan + Shay", mood: "Happy", genre: "Country", url: "https://www.youtube.com/embed/7UoP9ABJXGE")
Song.create(title: "Tequila", artist: "Dan + Shay", mood: "Lit", genre: "Country", url: "https://www.youtube.com/embed/c4qgqNS_20s")
Song.create(title: "Crash My Party", artist: "Luke Bryan", mood: "Happy", genre: "Country", url: "https://www.youtube.com/embed/1WEpLzsdEeY")
Song.create(title: "Make It Sweet", artist: "Old Dominion", mood: "Happy", genre: "Country", url: "https://www.youtube.com/embed/CJ9L4PewTuY")
Song.create(title: "Hotel Key", artist: "Old Dominion", mood: "Happy", genre: "Country", url: "https://www.youtube.com/embed/qZIx9CRRSq8")
Song.create(title: "Cruise", artist: "Florida Georgia Line", mood: "Lit", genre: "Country", url: "https://www.youtube.com/embed/8PvebsWcpto")
Song.create(title: "This Is How We Roll ft. Luke Bryan", artist: "Florida Georgia Line", mood: "Lit", genre: "Country", url: "https://www.youtube.com/embed/CbxuXq_981s")
Song.create(title: "Bless the Broken Road", artist: "Rascal Flatts", mood: "Happy", genre: "Country", url: "https://www.youtube.com/embed/Do32g82qilk")
Song.create(title: "Love Wins", artist: "Carrie Underwood", mood: "Lit", genre: "Country", url: "https://www.youtube.com/embed/-Py8OWAMkns")
Song.create(title: "House Party", artist: "Sam Hunt", mood: "Lit", genre: "Country", url: "https://www.youtube.com/embed/1FhRhzAWzLA")
Song.create(title: "Wanted", artist: "Hunter Hayes", mood: "Happy", genre: "Country", url: "https://www.youtube.com/embed/ruyaKdPfTN4")
Song.create(title: "Heaven", artist: "Kane Brown", mood: "Happy", genre: "Country", url: "https://www.youtube.com/embed/dRX0wDNK6S4")
Song.create(title: "Smile", artist: "Uncle Kracker", mood: "Happy", genre: "Country", url: "https://www.youtube.com/embed/ffej15-Dgl0")
Song.create(title: "Drift Away", artist: "Uncle Kracker", mood: "Lit", genre: "Country", url: "https://www.youtube.com/embed/A69BertdSt4")

Song.create(title: "Best Song Ever", artist: "One Direction", mood: "Happy", genre: "Pop", url: "https://www.youtube.com/embed/o_v9MY_FMcw")
Song.create(title: "Beautiful Soul", artist: "Jesse McCartney", mood: "Relaxed", genre: "Pop", url: "https://www.youtube.com/embed/ek2PDE1cAyY")
Song.create(title: "Domino", artist: "Jessie J", mood: "Lit", genre: "Pop", url: "https://www.youtube.com/embed/UJtB55MaoD0")
Song.create(title: "Teenage Dream", artist: "Katy Perry", mood: "Lit", genre: "Pop", url: "https://www.youtube.com/embed/98WtmW-lfeE")
Song.create(title: "Party In The U.S.A.", artist: "Miley Cyrus", mood: "Lit", genre: "Pop", url: "https://www.youtube.com/embed/M11SvDtPBhA")
Song.create(title: "Love Story", artist: "Taylor Swift", mood: "Happy", genre: "Pop", url: "https://www.youtube.com/embed/8xg3vE8Ie_E")
Song.create(title: "Love Yourself", artist: "Justin Bieber", mood: "Relaxed", genre: "Pop", url: "https://www.youtube.com/embed/oyEuk8j8imI")
Song.create(title: "Toxic", artist: "Britney Spears", mood: "Angry", genre: "Pop", url: "https://www.youtube.com/embed/LOZuxwVk7TU")
Song.create(title: "I Want It That Way", artist: "Backstreet Boys", mood: "Sad", genre: "Pop", url: "https://www.youtube.com/embed/4fndeDfaWCg")
Song.create(title: "Tearin' Up My Heart", artist: "*NSYNC", mood: "Sad", genre: "Pop", url: "https://www.youtube.com/embed/_ZcmuKsyvzg")
Song.create(title: "Can't Stop The Feeling", artist: "Justin Timberlake", mood: "Happy", genre: "Pop", url: "https://www.youtube.com/embed/ru0K8uYEZWw")
Song.create(title: "Bad Blood", artist: "Taylor Swift", mood: "Angry", genre: "Pop", url: "https://www.youtube.com/embed/QcIy9NiNbmo")
Song.create(title: "Bad Romance", artist: "Lady Gaga", mood: "Angry", genre: "Pop", url: "https://www.youtube.com/embed/qrO4YZeyl0I")
Song.create(title: "TiK ToK", artist: "Ke$ha", mood: "Lit", genre: "Pop", url: "https://www.youtube.com/embed/iP6XpLQM2Cs")
Song.create(title: "Call Me Maybe", artist: "Carly Rae Jepsen", mood: "Happy", genre: "Pop", url: "https://www.youtube.com/embed/fWNaR-rxAic")
Song.create(title: "Shape Of You", artist: "Ed Sheeran", mood: "Relaxed", genre: "Pop", url: "https://www.youtube.com/embed/JGwWNGJdvx8")
Song.create(title: "Perfect", artist: "Ed Sheeran", mood: "Relaxed", genre: "Pop", url: "https://www.youtube.com/embed/2Vv-BfVoq4g")
Song.create(title: "Hello", artist: "Adele", mood: "Sad", genre: "Pop", url: "https://www.youtube.com/embed/YQHsXMglC9A")
Song.create(title: "Sad Song ft. Elena Coats", artist: "We The Kings", mood: "Sad", genre: "Pop", url: "https://www.youtube.com/embed/BZsXcc_tC-o")
Song.create(title: "See You Again ft. Charlie Puth", artist: "Wiz Khalifa", mood: "Sad", genre: "Pop", url: "https://www.youtube.com/embed/RgKAFK5djSk")
Song.create(title: "Dark Horse", artist: "Katy Perry", mood: "Angry", genre: "Pop", url: "https://www.youtube.com/embed/0KSOMA3QBU0")
Song.create(title: "The Way", artist: "Ariana Grande", mood: "Happy", genre: "Pop", url: "https://www.youtube.com/embed/_sV0S8qWSy0")
Song.create(title: "Cry Me A River", artist: "Justin Timberlake", mood: "Angry", genre: "Pop", url: "https://www.youtube.com/embed/DksSPZTZES0")
Song.create(title: "Bleeding Love", artist: "Leona Lewis", mood: "Sad", genre: "Pop", url: "https://www.youtube.com/embed/7_weSk0BonM")
Song.create(title: "Just A Dream", artist: "Nelly", mood: "Sad", genre: "Pop", url: "https://www.youtube.com/embed/N6O2ncUKvlg")
Song.create(title: "Raise Your Glass", artist: "P!nk", mood: "Lit", genre: "Pop", url: "https://www.youtube.com/embed/XjVNlG5cZyQ")
Song.create(title: "A Thousand Miles", artist: "Vanessa Carlton", mood: "Relaxed", genre: "Pop", url: "https://www.youtube.com/embed/Cwkej79U3ek")
Song.create(title: "Because Of You", artist: "Kelly Clarkson", mood: "Angry", genre: "Pop", url: "https://www.youtube.com/embed/Ra-Om7UMSJc")
Song.create(title: "(You Drive Me) Crazy", artist: "Britney Spears", mood: "Happy", genre: "Pop", url: "https://www.youtube.com/embed/Q4VK9_CfOLQ")
Song.create(title: "Pocketful of Sunshine", artist: "Natasha Bedingfield", mood: "Happy", genre: "Pop", url: "https://www.youtube.com/embed/gte3BoXKwP0")
Song.create(title: "Genie in a Bottle", artist: "Christina Aguilera", mood: "Lit", genre: "Pop", url: "https://www.youtube.com/embed/kIDWgqDBNXA")
Song.create(title: "Wannabe", artist: "Spice Girls", mood: "Lit", genre: "Pop", url: "https://www.youtube.com/embed/gJLIiF15wjQ")
Song.create(title: "Be Alright", artist: "Ariana Grande", mood: "Relaxed", genre: "Pop", url: "https://www.youtube.com/embed/eBAHqRnSgRw")
Song.create(title: "Take A Bow", artist: "Rihanna", mood: "Angry", genre: "Pop", url: "https://www.youtube.com/embed/J3UjJ4wKLkg")
Song.create(title: "What Makes You Beautiful", artist: "One Direction", mood: "Relaxed", genre: "Pop", url: "https://www.youtube.com/embed/QJO3ROT-A4E")



Song.create(title: "Perfect", artist: "Simple Plan", mood: "Sad", genre: "Rock", url: "https://www.youtube.com/embed/RUi54JTgL5s")
Song.create(title: "Untitled", artist: "Simple Plan", mood: "Sad", genre: "Rock", url: "https://www.youtube.com/embed/ZQ7oqmikZDQ")
Song.create(title: "I'd Do Anything", artist: "Simple Plan", mood: "Lit", genre: "Rock", url: "https://www.youtube.com/embed/H2M7zo8ZziE")
Song.create(title: "Numb", artist: "Linkin Park", mood: "Angry", genre: "Rock", url: "https://www.youtube.com/embed/kXYiU_JCYtU")
Song.create(title: "Crawling", artist: "Linkin Park", mood: "Angry", genre: "Rock", url: "https://www.youtube.com/embed/Gd9OhYroLN0")
Song.create(title: "American Idiot", artist: "Green Day", mood: "Lit", genre: "Rock", url: "https://www.youtube.com/embed/Ee_uujKuJMI")
Song.create(title: "Boulevard Of Broken Dreams", artist: "Green Day", mood: "Sad", genre: "Rock", url: "https://www.youtube.com/embed/Soa3gO7tL-c")
Song.create(title: "I Miss You", artist: "Blink-182", mood: "Sad", genre: "Rock", url: "https://www.youtube.com/embed/s1tAYmMjLdY")
Song.create(title: "All The Small Things", artist: "Blink-182", mood: "Happy", genre: "Rock", url: "https://www.youtube.com/embed/9Ht5RZpzPqw")
Song.create(title: "Always", artist: "Blink-182", mood: "Relaxed", genre: "Rock", url: "https://www.youtube.com/embed/CvtJVku_mJw")
Song.create(title: "All Star", artist: "Smash Mouth", mood: "Relaxed", genre: "Rock", url: "https://www.youtube.com/embed/L_jWHffIx5E")
Song.create(title: "I'm A Believer", artist: "Smash Mouth", mood: "Happy", genre: "Rock", url: "https://www.youtube.com/embed/0mYBSayCsH0")
Song.create(title: "In Too Deep", artist: "Sum 41", mood: "Lit", genre: "Rock", url: "https://www.youtube.com/embed/emGri7i8Y2Y")
Song.create(title: "The Middle", artist: "Jimmy Eat World", mood: "Happy", genre: "Rock", url: "https://www.youtube.com/embed/oKsxPW6i3pM")
Song.create(title: "Stacy's Mom", artist: "Fountains of Wayne", mood: "Lit", genre: "Rock", url: "https://www.youtube.com/embed/dZLfasMPOU4")
Song.create(title: "Ocean Avenue", artist: "Yellowcard", mood: "Relaxed", genre: "Rock", url: "https://www.youtube.com/embed/X9fLbfzCqWw")
Song.create(title: "1985", artist: "Bowling For Soup", mood: "Relaxed", genre: "Rock", url: "https://www.youtube.com/embed/K38xNqZvBJI")
Song.create(title: "Be My Escape", artist: "Relient K", mood: "Sad", genre: "Rock", url: "https://www.youtube.com/embed/lt-FPtnyxvs")
Song.create(title: "Who I Am Hates Who I've Been", artist: "Relient K", mood: "Angry", genre: "Rock", url: "https://www.youtube.com/embed/8HeuMiuj_Sg")
Song.create(title: "Mr. Brightside", artist: "The Killers", mood: "Angry", genre: "Rock", url: "https://www.youtube.com/embed/gGdGFtwCNBE")
Song.create(title: "Let It Be", artist: "The Beatles", mood: "Relaxed", genre: "Rock", url: "https://www.youtube.com/embed/QDYfEBY9NM4")
Song.create(title: "Wonderwall", artist: "Oasis", mood: "Relaxed", genre: "Rock", url: "https://www.youtube.com/embed/bx1Bh8ZvH84")
Song.create(title: "Complicated", artist: "Avril Lavigne", mood: "Angry", genre: "Rock", url: "https://www.youtube.com/embed/5NPBIwQyPWE")
Song.create(title: "Iris", artist: "Goo Goo Dolls", mood: "Sad", genre: "Rock", url: "https://www.youtube.com/embed/NdYWuo9OFAw")
Song.create(title: "How to Save a Life", artist: "The Fray", mood: "Sad", genre: "Rock", url: "https://www.youtube.com/embed/cjVQ36NhbMk")
Song.create(title: "You and Me", artist: "Lifehouse", mood: "Happy", genre: "Rock", url: "https://www.youtube.com/embed/ac3HkriqdGQ")
Song.create(title: "It's My Life", artist: "Bon Jovi", mood: "Lit", genre: "Rock", url: "https://www.youtube.com/embed/vx2u5uUu3DE")
Song.create(title: "Livin' On A Prayer", artist: "Bon Jovi", mood: "Happy", genre: "Rock", url: "https://www.youtube.com/embed/lDK9QqIzhwk")
Song.create(title: "The Pretender", artist: "Foo Fighters", mood: "Angry", genre: "Rock", url: "https://www.youtube.com/embed/SBjQ9tuuTJQ")

Song.create(title:"Suicidal Thoughts", artist:"The Notorious B.I.G.", mood:"sad", genre:"Hip hop", url:"https://www.youtube.com/embed/GygEAcFFMVs" )
Song.create(title:"Marvin's Room", artist:"Drake", mood:"sad", genre:"Hip hop", url:"https://www.youtube.com/embed/JDb3ZZD4bA0" )
Song.create(title:"u", artist:"Kendrick Lamar", mood:"sad", genre:"Hip hop", url:"https://www.youtube.com/embed/QiTAqBKqJks" )
Song.create(title:"Summertime", artist:"Vince Staples", mood:"sad", genre:"Hip hop", url:"https://www.youtube.com/embed/lYSJU0MW-Ro" )
Song.create(title:"Acid Rain", artist:"Chance the Rapper", mood:"sad", genre:"Hip hop", url:"https://www.youtube.com/embed/U1AOoHSijIk" )
Song.create(title:"Moon River", artist: "Frank Ocean", mood:"sad", genre:"Hip hop", url:"https://www.youtube.com/embed/U1AOoHSijIk" )
Song.create(title:"8 Million Stories", artist:"A Tribe Called Quest", mood:"sad", genre:"Hip hop", url:"https://www.youtube.com/embed/KU1aVvP4f-E" )
Song.create(title:"Ballad of Worms", artist:"Cage", mood:"sad", genre:"Hip hop", url:"https://www.youtube.com/embed/Uqir_N9nkTA" )
Song.create(title:"Stay", artist:"Rihanna", mood:"sad", genre:"Hip hop", url:"https://www.youtube.com/watch?v=JF8BRvqGCNs" )

Song.create(title:"Act Up", artist:"City Girls", mood:"lit", genre:"Hip hop", url:"https://www.youtube.com/embed/UrfIZgAfhAM" )
Song.create(title:"Numb Numb Juice", artist:"ScHoolboy Q", mood:"lit", genre:"Hip hop", url:"https://www.youtube.com/embed/5_qAwMHhkwQ" )
Song.create(title:"Big Ole Freak", artist:"Megan Thee Stallion", mood:"lit", genre:"Hip hop", url:"https://www.youtube.com/embed/oBYf6gpVvRA" )
Song.create(title:"Nice For What", artist:"Drake", mood:"lit", genre:"Hip hop", url:"https://www.youtube.com/embed/U9BwWKXjVaI" )
Song.create(title:"Upgrade u", artist:"Beyonce ft. Jay Z", mood:"lit", genre:"Hip hop", url:"https://www.youtube.com/embed/6nr8hPnZfMU" )
Song.create(title:"Money", artist:"Cardi B", mood:"lit", genre:"Hip hop", url:"https://www.youtube.com/embed/zUOh09GoQgk" )
Song.create(title:"Thotiana", artist:"Blueface", mood:"lit", genre:"Hip hop", url:"https://www.youtube.com/embed/V6EpIABAKKo" )
Song.create(title:"APESHIT", artist:"The Carters", mood:"lit", genre:"Hip hop", url:"https://www.youtube.com/embed/V6EpIABAKKo" )
Song.create(title:"REEL IT IN", artist:"Amine", mood:"lit", genre:"Hip hop", url:"https://www.youtube.com/embed/QIwWYXJbxGY" )
Song.create(title:"ICY GRL", artist:"Saweetie", mood:"lit", genre:"Hip hop", url:"https://www.youtube.com/embed/Wji4b2jjYOk" )
Song.create(title:"Work", artist:"Rihanna ft. Drake", mood:"lit", genre:"Hip hop", url:"https://www.youtube.com/embed/puxjq3p-fU0" )
Song.create(title:"Lose Control", artist:"Missy Elliot ft. Ciara & Fatman Scoop", mood:"lit", genre:"Hip hop", url:"https://www.youtube.com/embed/na7lIb09898" )


Song.create(title:"Broccoli", artist:"Dram ft. Lil Yachty", mood:"happy", genre:"Hip hop", url:"https://www.youtube.com/embed/K44j-sb1SRY" )
Song.create(title:"No Problem", artist:"Chance the Rapper ft. 2 Chainz & Lil Wayne", mood:"happy", genre:"Hip hop", url:"https://www.youtube.com/embed/DVkkYlQNmbc" )
Song.create(title:"Hey Ya!", artist:"OutKast", mood:"happy", genre:"Hip hop", url:"https://www.youtube.com/embed/PWgvGjAhvIw" )
Song.create(title:"Up Up Away", artist:"", mood:"happy", genre:"Hip hop", url:"https://www.youtube.com/embed/qRPpLGxGNZY" )
Song.create(title:"Party", artist:"Beyonce ft. J. Cole", mood:"happy", genre:"Hip hop", url:"https://www.youtube.com/embed/XWCwc1_sYMY" )
Song.create(title:"Hello", artist:"Erykah Badu", mood:"happy", genre:"Hip hop", url:"https://www.youtube.com/embed/KXGqHYNTNHU" )
Song.create(title:"Love On Top", artist:"Beyonce", mood:"happy", genre:"Hip hop", url:"https://www.youtube.com/embed/Ob7vObnFUJc" )


Song.create(title:"Sorry", artist:"Beyonce", mood:"angry", genre:"Hip hop", url:"https://www.youtube.com/embed/QxsmWxxouIM" )
Song.create(title:"gun smoke", artist:"21 Savage", mood:"angry", genre:"Hip hop", url:"https://www.youtube.com/embed/HdgsbpNlJyM" )
Song.create(title:"Energy", artist:"Drake", mood:"angry", genre:"Hip hop", url:"https://www.youtube.com/embed/7LnBvuzjpr4" )
Song.create(title:"Knuck If You Buck", artist:"Crime Mob", mood:"angry", genre:"Hip hop", url:"https://www.youtube.com/embed/9saEpqhBP5M" )
Song.create(title:"Can't Tell Me Nothing", artist:"Kanye", mood:"angry", genre:"Hip hop", url:"https://www.youtube.com/embed/E58qLXBfLrs" )
Song.create(title:"Worst Behavior", artist:"Drake", mood:"angry", genre:"Hip hop", url:"https://www.youtube.com/embed/CccnAvfLPvE" )
Song.create(title:"Break The Bank", artist:"Schoolboy Q", mood:"angry", genre:"Hip hop", url:"https://www.youtube.com/embed/rc-Vqcud32I" )
Song.create(title:"Alright", artist:"Kendrick Lamar", mood:"angry", genre:"Hip hop", url:"" )



Song.create(title:"9", artist:"Willow & SZA", mood:"relaxed", genre:"Hip hop", url:"https://www.youtube.com/embed/usuHRa9MNIc" )
Song.create(title:"Pink + White", artist:"Frank Ocean", mood:"relaxed", genre:"Hip hop", url:"https://www.youtube.com/embed/uzS3WG6__G4" )
Song.create(title:"After The Storm", artist:"Kali Uchis ft. Tyler The Creator & Bootsy Collins", mood:"relaxed", genre:"Hip hop", url:"https://www.youtube.com/embed/9f5zD7ZSNpQ" )
Song.create(title:"While We're Young", artist:"Jhene Aiko", mood:"relaxed", genre:"Hip hop", url:"https://www.youtube.com/embed/LjvwRSKVQNs" )
Song.create(title:"Down", artist:"Chloe x Halle", mood:"relaxed", genre:"Hip hop", url:"https://www.youtube.com/embed/4PP9CrGZolY" )
Song.create(title:"Feather", artist:"Nujabes", mood:"relaxed", genre:"Hip hop", url:"https://www.youtube.com/embed/M-BWXT3UBns" )
Song.create(title:"Get You", artist:"Daniel Ceasar ft. Kali Uchis", mood:"relaxed", genre:"Hip hop", url:"" )
Song.create(title:"", artist:"Daniel Ceasar ft. Kali Uchis", mood:"relaxed", genre:"Hip hop", url:"" )
Song.create(title:"Cranes in the Sky", artist:"Solange", mood:"relaxed", genre:"Hip hop", url:"https://www.youtube.com/embed/S0qrinhNnOM" )
Song.create(title:"Slow Down", artist:"Mac Ayres", mood:"relaxed", genre:"Hip hop", url:"https://www.youtube.com/embed/bASJnkX60go" )
Song.create(title:"CPR", artist:"Summer Walker", mood:"relaxed", genre:"Hip hop", url:"https://www.youtube.com/embed/1eomjy9Xy3M" )
Song.create(title:"Bad Blood", artist:"Nao", mood:"relaxed", genre:"Hip hop", url:"https://www.youtube.com/embed/RSXhN7Pa4tk" )



Song.create(title:"That's What I Love About Sunday", artist:"Craig Morgan", mood:"relaxed", genre:"Country", url:"https://www.youtube.com/embed/pm3aCyRD3Vg")
Song.create(title:"Toes", artist:"Zac Brown Band", mood:"relaxed", genre:"Country", url:"https://www.youtube.com/embed/lB8Nkn3Xjes")
Song.create(title:"No Shoes, No Shirt, No Problem", artist:"Kenny Chesney", mood:"relaxed", genre:"Country", url:"https://www.youtube.com/embed/-01jhW_Yzhs")
Song.create(title:"Pontoon", artist:"Little Big Town", mood:"relaxed", genre:"Country", url:"https://www.youtube.com/embed/V0O0nzkESTI")
Song.create(title:"Strawberry Wine", artist:"Deana Carter", mood:"relaxed", genre:"Country", url:"https://www.youtube.com/embed/Up06CryWQpE")
Song.create(title:"Waitin' On A Woman", artist:"Brad Paisley", mood:"relaxed", genre:"Country", url:"https://www.youtube.com/embed/M-C-IbkuNWs")
Song.create(title:"When You Say Nothing At All", artist:"Alison Krauss", mood:"relaxed", genre:"Country", url:"https://www.youtube.com/embed/1SCOimBo5tg")

Song.create(title:"The Thunder Rolls", artist:"Garth Brooks", mood:"angry", genre:"Country", url:"https://www.youtube.com/embed/N7KNiPbPccU")
Song.create(title:"Before he Cheats", artist:"Carrie Underwood", mood:"angry", genre:"Country", url:"https://www.youtube.com/embed/WaSy8yy-mr8")
Song.create(title:"A Boy Named Sue", artist:"Johnny Cash", mood:"angry", genre:"Country", url:"https://www.youtube.com/embed/WOHPuY88Ry4")
Song.create(title:"Gunpowder and Lead", artist:"Miranda Lambert", mood:"angry", genre:"Country", url:"https://www.youtube.com/embed/aWQdEDtveB0")
Song.create(title:"These Boots Are Made for Walkin", artist:"Nancy Sinatra", mood:"angry", genre:"Country", url:"https://www.youtube.com/embed/MnQcExGaEvk")
Song.create(title:"Goodbye Earl", artist:"Dixie Chicks", mood:"angry", genre:"Country", url:"https://www.youtube.com/embed/Gw7gNf_9njs")
Song.create(title:"Two Black Cadillacs", artist:"Carrie Underwood", mood:"angry", genre:"Country", url:"https://www.youtube.com/embed/oVEBZLrjpw4")

Song.create(title:"She Thinks His Name Was John", artist:"Reba McEntire", mood:"sad", genre:"Country", url:"https://www.youtube.com/embed/jHmNksnUFdc")
Song.create(title:"Concrete Angel", artist:"Martina McBride", mood:"sad", genre:"Country", url:"")
Song.create(title:"What Hurts The Most", artist:"Rascal Flatts", mood:"sad", genre:"Country", url:"https://www.youtube.com/embed/7qH4qyi1-Ys")
Song.create(title:"The Dance", artist:"Garth Brooks", mood:"sad", genre:"Country", url:"https://www.youtube.com/embed/bpwdwbO1uvM")
Song.create(title:"Fire Away", artist:"Chris Stapleton", mood:"sad", genre:"Country", url:"https://www.youtube.com/embed/ZI-aPHeUDlk")
Song.create(title:"Hurt", artist:"Johnny Cash", mood:"sad", genre:"Country", url:"https://www.youtube.com/embed/vt1Pwfnh5pc")
Song.create(title:"Tonight I Wanna Cry", artist:"Keith Urban", mood:"sad", genre:"Country", url:"https://www.youtube.com/embed/fmO1u3ONYg8")
